### ISSUE TITLE
less.js doesn't work on iOS 5

### ISSUE THREAD

**Issue by honigferd** [less/less.js#1723]
After upgrading less.js to 1.5.0, all our iOS 5 devices return following error:

SyntaxError: 'undefined' is not a function
in lessfile.less on line 0, column 0

I can reproduce this error on less2css.org aswell.
